import type { ProgramItem } from './types';

export const MASTER_PROGRAMS: ProgramItem[] = [
    // ── 1. PILAR DAKWAH & PEMBINAAN ──
    {
        id: '1',
        slug: 'pembangunan-markaz',
        title: 'Pembangunan Markaz Dakwah & Kaderisasi Dai',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 2004000000,
        targetFormatted: 'Rp 2.004.000.000',
        collected: 486500000,
        collectedFormatted: 'Rp 486.500.000',
        donorsCount: 312,
        daysLeft: 120,
        description: 'Dukung pembangunan pusat kegiatan dakwah, kaderisasi da\'i, dan pembinaan umat di pelosok Bangka Belitung untuk mencetak generasi Rabbani yang kokoh dan berakhlak mulia.',
        fullDescription: 'Pusat Markaz Dakwah WIZ Bangka Belitung didirikan sebagai sentra pembinaan spiritual, kajian Islam intensif, pencetakan kader da\'i yang siap diterjunkan ke pulau-pulau terpencil, serta asrama pembinaan santri dan mualaf.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Pangkalpinang, Bangka Belitung',
        beneficiaries: 'Santri, Da\'i, & Masyarakat Umum',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: '2',
        slug: 'pengadaan-perbaikan-kendaraan',
        title: 'Pengadaan & Perbaikan Kendaraan Operasional Dai',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 5000000,
        targetFormatted: 'Rp 5.000.000',
        collected: 3750000,
        collectedFormatted: 'Rp 3.750.000',
        donorsCount: 45,
        daysLeft: 25,
        description: 'Fasilitasi mobilitas para da\'i dalam menyebarkan syiar Islam ke pelosok desa dan pesisir Bangka Belitung dengan armada kendaraan operasional yang layak.',
        fullDescription: 'Banyak titik binaan dakwah terletak di pelosok desa yang sulit dijangkau transportasi umum. Bantuan pengadaan dan servis kendaraan ini memastikan para da\'i dapat berdakwah secara aman dan konsisten.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Bangka & Belitung',
        beneficiaries: 'Da\'i Pelosok & Titik Binaan',
        featured: false,
        active: true
    },
    {
        id: '3',
        slug: 'keberangkatan-kepulangan-dai',
        title: 'Kafalah & Transportasi Dai Pelosok',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 30000000,
        targetFormatted: 'Rp 30.000.000',
        collected: 21500000,
        collectedFormatted: 'Rp 21.500.000',
        donorsCount: 88,
        daysLeft: 40,
        description: 'Dukungan akomodasi, transportasi kepulangan dan keberangkatan, serta kafalah bulanan bagi para da\'i yang mengabdi membina masyarakat di pelosok Bangka Belitung.',
        fullDescription: 'Para da\'i mendedikasikan hidupnya mengajar Al-Qur\'an dan aqidah di pelosok. Melalui program ini, kita bersama-sama menopang kebutuhan operasional dan kesejahteraan mereka.',
        imageUrl: '/assets/images/keberangkatan-kepulangan-dai.jpg',
        location: 'Kepulauan Bangka Belitung',
        beneficiaries: 'Da\'i & Ustadz Pembina Umat',
        featured: true,
        active: true
    },
    {
        id: '4',
        slug: 'santunan-mualaf',
        title: 'Santunan & Pembinaan Mualaf Pelosok',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 12000000,
        targetFormatted: 'Rp 12.000.000',
        collected: 8900000,
        collectedFormatted: 'Rp 8.900.000',
        donorsCount: 64,
        daysLeft: 30,
        description: 'Berikan dukungan moral, materiil, dan bimbingan agama bagi saudara-saudara kita para mualaf agar semakin teguh memeluk dan mengamalkan ajaran Islam.',
        fullDescription: 'Program pendampingan mualaf mencakup bantuan logistik, perlengkapan sholat, buku tuntunan ibadah, serta pembinaan rutin bersama da\'i pembina.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Bangka & Belitung',
        beneficiaries: 'Saudara Mualaf',
        featured: false,
        active: true
    },
    {
        id: '5',
        slug: 'tahfidz-weekend',
        title: 'Tahfidz Weekend & Konsumsi Penghafal Quran',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 15000000,
        targetFormatted: 'Rp 15.000.000',
        collected: 11400000,
        collectedFormatted: 'Rp 11.400.000',
        donorsCount: 92,
        daysLeft: 18,
        description: 'Dukung para penghafal Al-Qur\'an dalam menjaga kalamullah dengan sedekah konsumsi dan fasilitas belajar di program Tahfidz Weekend rutin.',
        fullDescription: 'Program menghafal Al-Qur\'an intensif di akhir pekan bagi santri dan generasi muda di Masjid Kemas Adil (Jl. Ahmad Yani) dengan bimbingan ustadz mutqin.',
        imageUrl: '/assets/images/logo-wiz-babel.png',
        location: 'Masjid Kemas Adil (Jl. Ahmad Yani, Pangkalpinang)',
        beneficiaries: 'Penghafal Al-Qur\'an & Santri',
        featured: true,
        active: true
    },
    {
        id: '6',
        slug: 'pelatihan-public-speaking',
        title: 'Pelatihan Public Speaking & Retorika Dakwah',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 4000000,
        targetFormatted: 'Rp 4.000.000',
        collected: 2800000,
        collectedFormatted: 'Rp 2.800.000',
        donorsCount: 30,
        daysLeft: 15,
        description: 'Tingkatkan kapasitas komunikasi, retorika, dan dakwah para da\'i muda serta relawan dakwah di Bangka Belitung.',
        fullDescription: 'Workshop pelatihan intensif public speaking untuk melahirkan da\'i yang komunikatif, artikulatif, dan mampu menyampaikan pesan kebaikan secara memikat.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Pangkalpinang',
        beneficiaries: 'Da\'i Muda & Relawan',
        featured: false,
        active: true
    },
    {
        id: '7',
        slug: 'tabligh-akbar-dzulhijjah',
        title: 'Tabligh Akbar & Semarak Syiar Islam',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 10000000,
        targetFormatted: 'Rp 10.000.000',
        collected: 7500000,
        collectedFormatted: 'Rp 7.500.000',
        donorsCount: 52,
        daysLeft: 35,
        description: 'Menghadirkan da\'i nasional untuk menggelorakan syiar Islam, penguatan akidah, dan persatuan ummat di Bangka Belitung.',
        fullDescription: 'Kajian akbar terbuka untuk masyarakat umum guna meningkatkan kecintaan kepada syariat Islam dan mempererat ukhuwah islamiyah.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Masyarakat Umum',
        featured: false,
        active: true
    },
    {
        id: '8',
        slug: 'pelatihan-guru-dirosa',
        title: 'Pelatihan & Sertifikasi Guru Al-Quran Dirosa',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 6000000,
        targetFormatted: 'Rp 6.000.000',
        collected: 4200000,
        collectedFormatted: 'Rp 4.200.000',
        donorsCount: 38,
        daysLeft: 22,
        description: 'Mencetak pengajar Al-Qur\'an metode Dirosa (Pendidikan Al-Qur\'an Orang Dewasa) agar bebas buta aksara Qur\'an.',
        fullDescription: 'Pelatihan metode cepat belajar membaca Al-Qur\'an bagi orang dewasa untuk mencetak para pengajar handal di berbagai masjid dan majelis taklim.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Pangkalpinang & sekitarnya',
        beneficiaries: 'Calon Guru Ngaji Dewasa',
        featured: false,
        active: true
    },
    {
        id: '9',
        slug: 'pelatihan-penyelenggaraan-jenazah',
        title: 'Pelatihan Fiqih Penyelenggaraan Jenazah',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 5000000,
        targetFormatted: 'Rp 5.000.000',
        collected: 3600000,
        collectedFormatted: 'Rp 3.600.000',
        donorsCount: 29,
        daysLeft: 20,
        description: 'Edukasi dan pelatihan praktikum tata cara memandikan, mengkafani, dan mensholatkan jenazah sesuai sunnah Rasulullah ﷺ.',
        fullDescription: 'Membekali masyarakat dan pengurus masjid dengan ilmu fardhu kifayah yang sangat penting ini melalui teori dan simulasi langsung.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Masjid-masjid di Bangka',
        beneficiaries: 'Masyarakat & Pengurus Masjid',
        featured: false,
        active: true
    },
    {
        id: '10',
        slug: 'pelatihan-relawan-media-dakwah',
        title: 'Pelatihan Relawan & Kreator Media Dakwah',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 4500000,
        targetFormatted: 'Rp 4.500.000',
        collected: 3100000,
        collectedFormatted: 'Rp 3.100.000',
        donorsCount: 25,
        daysLeft: 18,
        description: 'Membina generasi muda dalam memproduksi konten dakwah digital yang kreatif, inspiratif, dan menyejukkan.',
        fullDescription: 'Pelatihan desain grafis, videografi, dan copywriting dakwah untuk memaksimalkan media sosial sebagai sarana menebar kebaikan.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Pangkalpinang',
        beneficiaries: 'Pemuda & Relawan Media',
        featured: false,
        active: true
    },
    {
        id: '11',
        slug: 'kantor-dpw-wi-babel-dan-wiz',
        title: 'Operasional Kantor Pelayanan Umat DPW & WIZ',
        pillar: 'Dakwah & Pembinaan',
        category: 'Dakwah',
        target: 50000000,
        targetFormatted: 'Rp 50.000.000',
        collected: 28400000,
        collectedFormatted: 'Rp 28.400.000',
        donorsCount: 77,
        daysLeft: 60,
        description: 'Dukungan sarana prasarana pusat pelayanan donatur, konsultasi zakat, dan koordinasi program kemaslahatan umat.',
        fullDescription: 'Menjamin kelancaran roda organisasi dalam menghimpun dan menyalurkan amanah zakat, infak, dan sedekah secara profesional dan akuntabel.',
        imageUrl: '/assets/images/default-program-wiz.jpg',
        location: 'Jl. Ahmad Yani, Pangkalpinang',
        beneficiaries: 'Pelayanan Donatur & Mustahik',
        featured: false,
        active: true
    },

    // ── 2. PILAR PENDIDIKAN ──
    {
        id: '12',
        slug: 'beasiswa-pendidikan-juara',
        title: 'Beasiswa Pendidikan Generasi Juara',
        pillar: 'Pendidikan',
        category: 'Pendidikan',
        target: 50000000,
        targetFormatted: 'Rp 50.000.000',
        collected: 32800000,
        collectedFormatted: 'Rp 32.800.000',
        donorsCount: 142,
        daysLeft: 45,
        description: 'Bantu anak-anak berprestasi dari keluarga prasejahtera agar terus melanjutkan sekolah dan meraih cita-cita mulia mereka.',
        fullDescription: 'Memberikan beasiswa SPP, seragam, dan perlengkapan sekolah bagi siswa SD, SMP, hingga SMA dari keluarga dhuafa di Bangka Belitung.',
        imageUrl: '/assets/images/beasiswa-pendidikan-juara.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Anak Dhuafa Berprestasi',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: '13',
        slug: 'beasiswa-tahfidz',
        title: 'Beasiswa Santri Tahfidz Quran',
        pillar: 'Pendidikan',
        category: 'Pendidikan',
        target: 60000000,
        targetFormatted: 'Rp 60.000.000',
        collected: 41200000,
        collectedFormatted: 'Rp 41.200.000',
        donorsCount: 185,
        daysLeft: 50,
        description: 'Investasi akhirat dengan membiayai kebutuhan pendidikan, akomodasi, dan kitab bagi santri penghafal Al-Qur\'an.',
        fullDescription: 'Melahirkan penghafal Al-Qur\'an 30 juz yang berkarakter islami dan berwawasan luas dari kalangan yatim dan dhuafa di Bangka Belitung.',
        imageUrl: '/assets/images/beasiswa-tahfidz.jpg',
        location: 'Pesantren Tahfidz Bangka',
        beneficiaries: 'Santri Tahfidz Quran',
        featured: true,
        active: true
    },
    {
        id: '14',
        slug: 'perlengkapan-belajar-yatim',
        title: 'Paket Perlengkapan Belajar Anak Yatim',
        pillar: 'Pendidikan',
        category: 'Pendidikan',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 18700000,
        collectedFormatted: 'Rp 18.700.000',
        donorsCount: 96,
        daysLeft: 30,
        description: 'Hadiahkan tas, buku tulis, alat tulis, dan sepatu baru untuk mengukir senyum bahagia di wajah anak-anak yatim.',
        fullDescription: 'Penyaluran paket sekolah lengkap di awal tahun ajaran baru guna menumbuhkan semangat belajar adik-adik yatim piatu.',
        imageUrl: '/assets/images/perlengkapan-belajar-yatim.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Anak Yatim & Dhuafa',
        featured: false,
        active: true
    },

    // ── 3. PILAR SOSIAL & KEMANUSIAAN ──
    {
        id: '15',
        slug: 'tebar-iftar-nusantara',
        title: 'Tebar Iftar & Buka Puasa Berkah Nusantara',
        pillar: 'Sosial & Kemanusiaan',
        category: 'Sosial',
        target: 100000000,
        targetFormatted: 'Rp 100.000.000',
        collected: 73500000,
        collectedFormatted: 'Rp 73.500.000',
        donorsCount: 280,
        daysLeft: 20,
        description: 'Bagikan paket hidangan buka puasa bergizi bagi santri, dhuafa, musafir, dan masyarakat pelosok di bulan Ramadhan.',
        fullDescription: 'Setiap paket iftar membawa kegembiraan dan berkah pahala setara orang yang berpuasa. Disalurkan ke masjid-masjid kampung, panti asuhan, dan pelosok.',
        imageUrl: '/assets/images/tebar-iftar-nusantara.jpg',
        location: 'Seluruh Bangka Belitung',
        beneficiaries: 'Dhuafa, Santri, & Kaum Muslimin',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: '16',
        slug: 'santunan-yatim',
        title: 'Santunan & Kado Kasih Sayang Yatim Dhuafa',
        pillar: 'Sosial & Kemanusiaan',
        category: 'Sosial',
        target: 45000000,
        targetFormatted: 'Rp 45.000.000',
        collected: 34200000,
        collectedFormatted: 'Rp 34.200.000',
        donorsCount: 160,
        daysLeft: 35,
        description: 'Raih kedekatan bersama Rasulullah ﷺ di surga dengan memuliakan, menyantuni, dan membahagiakan anak-anak yatim.',
        fullDescription: 'Penyaluran santunan uang tunai, sembako, dan bingkisan kasih sayang bulanan bagi anak-anak yatim yang diasuh ibu tunggal atau keluarga dhuafa.',
        imageUrl: '/assets/images/santunan-yatim.jpg',
        location: 'Pangkalpinang, Sungailiat, Koba, Belitung',
        beneficiaries: 'Anak Yatim & Dhuafa',
        featured: true,
        active: true
    },
    {
        id: '17',
        slug: 'sedekah-beras-dhuafa',
        title: 'Sedekah Beras untuk Keluarga Dhuafa',
        pillar: 'Sosial & Kemanusiaan',
        category: 'Sosial',
        target: 35000000,
        targetFormatted: 'Rp 35.000.000',
        collected: 27900000,
        collectedFormatted: 'Rp 27.900.000',
        donorsCount: 135,
        daysLeft: 28,
        description: 'Pastikan tidak ada keluarga prasejahtera dan lansia dhuafa di Bangka Belitung yang tidur dalam keadaan menahan lapar.',
        fullDescription: 'Penyaluran beras premium 5kg - 10kg secara berkala untuk ribuan keluarga mustahik, buruh harian, janda tua, dan pekerja informal.',
        imageUrl: '/assets/images/sedekah-beras-dhuafa.jpg',
        location: 'Kabupaten & Kota se-Bangka Belitung',
        beneficiaries: 'Keluarga Mustahik & Lansia',
        featured: true,
        active: true
    },
    {
        id: '18',
        slug: 'tebar-sembako',
        title: 'Tebar Paket Sembako Berkah Ketahanan Pangan',
        pillar: 'Sosial & Kemanusiaan',
        category: 'Sosial',
        target: 40000000,
        targetFormatted: 'Rp 40.000.000',
        collected: 29500000,
        collectedFormatted: 'Rp 29.500.000',
        donorsCount: 110,
        daysLeft: 32,
        description: 'Bantuan paket kebutuhan pokok (minyak, gula, terigu, susu, telur) untuk meringankan beban ekonomi saudara kita yang membutuhkan.',
        fullDescription: 'Didistribusikan langsung secara door-to-door oleh relawan WIZ ke rumah-rumah warga kurang mampu di permukiman padat dan desa terpencil.',
        imageUrl: '/assets/images/tebar-sembako.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Keluarga Dhuafa',
        featured: false,
        active: true
    },
    {
        id: '19',
        slug: 'sedekah-beras-dai',
        title: 'Sedekah Beras Da\'i & Guru Ngaji Pelosok',
        pillar: 'Sosial & Kemanusiaan',
        category: 'Sosial',
        target: 18000000,
        targetFormatted: 'Rp 18.000.000',
        collected: 14600000,
        collectedFormatted: 'Rp 14.600.000',
        donorsCount: 82,
        daysLeft: 25,
        description: 'Menjamin ketahanan pangan para ustadz, guru ngaji kampung, dan da\'i yang tulus mengabdi membina ummat tanpa pamrih.',
        fullDescription: 'Bantuan beras bulanan untuk guru-guru mengaji tradisional yang ikhlas mengajarkan Al-Qur\'an di pelosok-pelosok desa.',
        imageUrl: '/assets/images/sedekah-beras-dai.jpg',
        location: 'Koba & Pelosok Bangka',
        beneficiaries: 'Guru Ngaji & Da\'i Kampung',
        featured: false,
        active: true
    },

    // ── 4. PILAR KESEHATAN ──
    {
        id: '20',
        slug: 'khitanan-massal-dhuafa',
        title: 'Khitanan Massal Berkah Anak Sholeh Dhuafa',
        pillar: 'Kesehatan',
        category: 'Kesehatan',
        target: 30000000,
        targetFormatted: 'Rp 30.000.000',
        collected: 22800000,
        collectedFormatted: 'Rp 22.800.000',
        donorsCount: 95,
        daysLeft: 25,
        description: 'Layanan khitan gratis dengan metode modern yang aman dan nyaman, disertai bingkisan sarung, baju koko, dan santunan.',
        fullDescription: 'Membantu anak-anak yatim dan dhuafa menunaikan kewajiban thaharah dengan ditangani tim dokter muslim profesional.',
        imageUrl: '/assets/images/khitanan-massal-dhuafa.jpg',
        location: 'Pangkalpinang & Sungailiat',
        beneficiaries: 'Anak Yatim & Dhuafa',
        featured: true,
        active: true
    },
    {
        id: '21',
        slug: 'ambulance-gratis-ummat',
        title: 'Ambulans Gratis & Layanan Tanggap Medis Ummat',
        pillar: 'Kesehatan',
        category: 'Kesehatan',
        target: 120000000,
        targetFormatted: 'Rp 120.000.000',
        collected: 68500000,
        collectedFormatted: 'Rp 68.500.000',
        donorsCount: 210,
        daysLeft: 75,
        description: 'Layanan armada ambulans dan mobil jenazah gratis 24 jam untuk pasien dhuafa, rujukan rumah sakit, dan pengantaran jenazah.',
        fullDescription: 'Armada siaga yang siap melayani kebutuhan darurat medis masyarakat prasejahtera di seluruh penjuru pulau Bangka tanpa dipungut biaya.',
        imageUrl: '/assets/images/ambulance-gratis-ummat.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Pasien Dhuafa & Masyarakat',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: '22',
        slug: 'bantuan-pengobatan',
        title: 'Bantuan Biaya Pengobatan Pasien Dhuafa',
        pillar: 'Kesehatan',
        category: 'Kesehatan',
        target: 40000000,
        targetFormatted: 'Rp 40.000.000',
        collected: 26300000,
        collectedFormatted: 'Rp 26.300.000',
        donorsCount: 118,
        daysLeft: 30,
        description: 'Bantu saudara kita yang menderita penyakit kronis atau butuh operasi namun terkendala biaya hidup dan obat non-BPJS.',
        fullDescription: 'Dukungan dana penunjang medis, transportasi rujukan luar pulau, dan pemenuhan nutrisi bagi pasien tidak mampu.',
        imageUrl: '/assets/images/bantuan-pengobatan.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Pasien Prasejahtera',
        featured: false,
        active: true
    },

    // ── 5. PILAR PEMBERDAYAAN EKONOMI & BENCANA ──
    {
        id: '23',
        slug: 'modal-usaha-dhuafa',
        title: 'Bantuan Modal Usaha & Kemandirian Dhuafa',
        pillar: 'Pemberdayaan Ekonomi & Bencana',
        category: 'Ekonomi',
        target: 50000000,
        targetFormatted: 'Rp 50.000.000',
        collected: 31700000,
        collectedFormatted: 'Rp 31.700.000',
        donorsCount: 105,
        daysLeft: 40,
        description: 'Bantuan modal usaha mikro tanpa riba serta pendampingan bisnis bagi mustahik agar bertransformasi menjadi muzakki yang mandiri.',
        fullDescription: 'Pemberian sarana usaha seperti gerobak, etalase, bahan baku dagang, dan literasi keuangan syariah untuk keluarga prasejahtera.',
        imageUrl: '/assets/images/modal-usaha-dhuafa.jpg',
        location: 'Bangka Belitung',
        beneficiaries: 'Pedagang Kecil & Mustahik Produktif',
        featured: true,
        active: true
    },
    {
        id: '24',
        slug: 'pelatihan-keterampilan-wirausaha',
        title: 'Pelatihan Keterampilan & UMKM Berdaya',
        pillar: 'Pemberdayaan Ekonomi & Bencana',
        category: 'Ekonomi',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 16400000,
        collectedFormatted: 'Rp 16.400.000',
        donorsCount: 68,
        daysLeft: 35,
        description: 'Membekali pemuda dan ibu-ibu rumah tangga dengan keahlian praktis bernilai ekonomi tinggi (kuliner, menjahit, digital marketing).',
        fullDescription: 'Program inkubasi kewirausahaan praktis untuk menciptakan sumber pendapatan baru bagi keluarga berpenghasilan rendah.',
        imageUrl: '/assets/images/pelatihan-keterampilan-wirausaha.jpg',
        location: 'Pangkalpinang & Sungailiat',
        beneficiaries: 'Pemuda & Ibu Rumah Tangga',
        featured: false,
        active: true
    },
    {
        id: '25',
        slug: 'tanggap-darurat-bencana',
        title: 'Tanggap Darurat Kebencanaan & Kemanusiaan',
        pillar: 'Pemberdayaan Ekonomi & Bencana',
        category: 'Bencana',
        target: 50000000,
        targetFormatted: 'Rp 50.000.000',
        collected: 38900000,
        collectedFormatted: 'Rp 38.900.000',
        donorsCount: 175,
        daysLeft: 60,
        description: 'Aksi cepat tanggap relawan WIZ dalam menyalurkan bantuan evakuasi, dapur umum, air bersih, dan logistik bagi korban bencana.',
        fullDescription: 'Kesiapsiagaan logistik dan tim relawan tanggap bencana untuk musibah banjir, angin puting beliung, kebakaran, dan krisis kemanusiaan.',
        imageUrl: '/assets/images/pray-for-ntt.jpg',
        location: 'Bangka Belitung & Titik Bencana Nasional',
        beneficiaries: 'Penyintas Bencana',
        featured: true,
        urgent: true,
        active: true
    }
];

export const BANK_ACCOUNTS = [
    {
        bankName: 'Bank Syariah Indonesia (BSI)',
        accountNumber: '4999 000 005',
        accountHolder: 'Wahdah Inspirasi Zakat',
        badge: 'Utama / Rekening Zakat & Infak'
    },
    {
        bankName: 'Bank Muamalat',
        accountNumber: '801 008 0005',
        accountHolder: 'Wahdah Inspirasi Zakat',
        badge: 'Inspirasi Sedekah'
    },
    {
        bankName: 'Bank Mandiri',
        accountNumber: '152 000 888 7771',
        accountHolder: 'Wahdah Inspirasi Zakat',
        badge: 'Operasional & Kemanusiaan'
    }
];
