import type { ProgramItem } from './types';

export const MASTER_PROGRAMS: ProgramItem[] = [
    // ── 1. PILAR BERKAH PEDULI (Sosial & Kemanusiaan) ──
    {
        id: 'prog-pray-for-ntt',
        slug: 'pray-for-ntt',
        title: 'Pray For NTT',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 50000000,
        targetFormatted: 'Rp 50.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 60,
        description: 'Salurkan kepedulian dan bantuan darurat bencana untuk saudara-saudara kita terdampak bencana di Nusa Tenggara Timur (NTT).',
        fullDescription: 'Program bantuan tanggap bencana darurat dan pemulihan bagi para penyintas bencana di NTT melalui penyediaan sembako, obat-obatan, tenda pengungsian, dan fasilitas ibadah.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Nusa Tenggara Timur (NTT)',
        beneficiaries: 'Warga & Penyintas Terdampak Bencana di NTT',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: 'prog-tebar-sembako',
        slug: 'tebar-sembako',
        title: 'Tebar Sembako',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Penyaluran paket bahan pangan pokok untuk keluarga dhuafa, janda lansia, dan yatim di pelosok Bangka Belitung.',
        fullDescription: 'Bantuan paket kebutuhan sembako (beras, minyak goreng, gula, tepung) secara langsung ke rumah warga prasejahtera di Bangka Belitung.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Kepulauan Bangka Belitung',
        beneficiaries: 'Keluarga Dhuafa & Lansia',
        featured: false,
        active: true
    },
    {
        id: 'prog-sedekah-beras-dhuafa',
        slug: 'sedekah-beras-dhuafa',
        title: 'Sedekah Beras Dhuafa',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 20000000,
        targetFormatted: 'Rp 20.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Bantuan beras premium secara berkala untuk mencukupi kebutuhan pokok para mustahik dan santri pondok pesantren.',
        fullDescription: 'Penyaluran beras berkah untuk keluarga dhuafa, pekerja serabutan, dan pondok tahfidz di berbagai titik binaan WIZ Bangka Belitung.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Mustahik & Santri Pesantren',
        featured: true,
        active: true
    },
    {
        id: 'prog-sedekah-jumat',
        slug: 'sedekah-jumat',
        title: 'Sedekah Jumat',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 15000000,
        targetFormatted: 'Rp 15.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Program Sedulang Berkah Sedekah Jumat untuk jamaah masjid, musafir, dan dhuafa di hari yang mulia.',
        fullDescription: 'Penyaluran hidangan makanan siap saji penuh berkah setiap hari Jumat kepada jamaah sholat Jumat, musafir, dan pekerja jalanan.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang & Sungailiat',
        beneficiaries: 'Jamaah Masjid & Dhuafa',
        featured: false,
        active: true
    },
    {
        id: 'prog-santunan-yatim',
        slug: 'santunan-yatim',
        title: 'Santunan Yatim',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 30000000,
        targetFormatted: 'Rp 30.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 45,
        description: 'Santunan bulanan dan pemenuhan kebutuhan primer anak-anak yatim dhuafa agar tumbuh bahagia.',
        fullDescription: 'Pemberian santunan uang saku, kado perlengkapan, dan pendampingan kasih sayang untuk anak-anak yatim prasejahtera.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Anak-Anak Yatim Dhuafa',
        featured: true,
        active: true
    },
    {
        id: 'prog-tebar-quran',
        slug: 'tebar-quran-nusantara',
        title: "Tebar Qur'an Nusantara",
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 20000000,
        targetFormatted: 'Rp 20.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 40,
        description: 'Distribusi mushaf Al-Qur\'an standar ke rumah tahfidz, TPQ, dan masjid pelosok daerah.',
        fullDescription: 'Sedekah jariyah mushaf Al-Qur\'an terjemahan dan mushaf hafalan untuk santri pelosok yang membutuhkan Al-Qur\'an layak.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Santri TPQ & Rumah Tahfidz',
        featured: false,
        active: true
    },
    {
        id: 'prog-tebar-iftar',
        slug: 'tebar-iftar-nusantara',
        title: 'Tebar Iftar Nusantara',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 30000000,
        targetFormatted: 'Rp 30.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Penyaluran paket makanan buka puasa penuh berkah dan gizi untuk santri serta dhuafa di Bangka Belitung.',
        fullDescription: 'Berbagi hidangan berbuka puasa di bulan suci Ramadhan bagi kaum dhuafa, anak yatim, dan santri penghafal Quran.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Santri & Kaum Dhuafa',
        featured: true,
        active: true
    },
    {
        id: 'prog-bahagiakan-guru-ngaji',
        slug: 'bahagiakan-guru-ngaji',
        title: 'Bahagiakan Guru Ngaji',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 35,
        description: 'Apresiasi tunjangan dan bingkisan sembako untuk guru ngaji tradisional yang ikhlas mengajar di pelosok.',
        fullDescription: 'Bentuk penghormatan dan pemuliaan atas dedikasi para ustadz dan guru ngaji kampung yang membina generasi Qur\'ani tanpa mengharap pamrih.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pelosok Bangka Belitung',
        beneficiaries: 'Guru Ngaji Tradisional',
        featured: false,
        active: true
    },
    {
        id: 'prog-sedekah-air',
        slug: 'sedekah-air',
        title: 'Sedekah Air',
        pillar: 'Berkah Peduli',
        category: 'Sosial & Kemanusiaan',
        target: 35000000,
        targetFormatted: 'Rp 35.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 50,
        description: 'Pembuatan sumur bor, instalasi pipa, dan penampungan air bersih untuk daerah rawan kekeringan.',
        fullDescription: 'Menghadirkan sumber air bersih mengalir bagi warga dan masjid di wilayah yang kerap dilanda krisis air bersih saat musim kemarau.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Titik Rawan Kekeringan Babel',
        beneficiaries: 'Masyarakat Umum & Masjid',
        featured: false,
        active: true
    },

    // ── 2. PILAR BERKAH HIDAYAH (Dakwah & Pembinaan) ──
    {
        id: 'prog-pembangunan-markaz',
        slug: 'pembangunan-markaz',
        title: 'Pembangunan Markaz',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 2004000000,
        targetFormatted: 'Rp 2.004.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 120,
        description: 'Dukung pembangunan pusat dakwah terpadu, markaz kaderisasi da\'i, dan asrama santri tahfidz WIZ Bangka Belitung.',
        fullDescription: 'Sentra kegiatan dakwah Islam, pelatihan da\'i pelosok, pembinaan mualaf, dan asrama santri tahfidz Al-Qur\'an.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang, Bangka Belitung',
        beneficiaries: 'Santri, Da\'i, & Kaum Muslimin',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: 'prog-kendaraan-dakwah',
        slug: 'pengadaan-perbaikan-kendaraan',
        title: 'Pengadaan & Perbaikan Kendaraan',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 35000000,
        targetFormatted: 'Rp 35.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Pengadaan armada mobil dan sepeda motor operasional untuk mobilitas para da\'i ke pelosok pedalaman.',
        fullDescription: 'Memastikan para da\'i memiliki sarana transportasi yang aman dan tangguh untuk menjangkau desa-desa binaan di pesisir dan pedalaman.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka & Belitung',
        beneficiaries: 'Da\'i Pelosok & Titik Binaan',
        featured: false,
        active: true
    },
    {
        id: 'prog-santunan-mualaf',
        slug: 'santunan-mualaf',
        title: 'Santunan Mualaf',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 20000000,
        targetFormatted: 'Rp 20.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Bimbingan aqidah, pelatihan ibadah, dan bantuan kemandirian hidup bagi saudara-saudara kita mualaf.',
        fullDescription: 'Program penguatan keimanan, penyediaan sarana sholat dan Al-Qur\'an, serta pendampingan ekonomi bagi mualaf baru.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Saudara Mualaf',
        featured: false,
        active: true
    },
    {
        id: 'prog-tahfidz',
        slug: 'tahfidz',
        title: 'Tahfidz',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 30000000,
        targetFormatted: 'Rp 30.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 40,
        description: 'Program beasiswa pembinaan santri penghafal Al-Qur\'an 30 juz berkarakter qur\'ani.',
        fullDescription: 'Mendukung santri tahfidz dalam menyelesaikan setoran hafalan 30 juz dengan bimbingan ustadz penghafal Al-Qur\'an mutqin.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Rumah Tahfidz WIZ Babel',
        beneficiaries: 'Santri Penghafal Al-Qur\'an',
        featured: true,
        active: true
    },
    {
        id: 'prog-public-speaking',
        slug: 'pelatihan-public-speaking',
        title: 'Pelatihan Public Speaking',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 10000000,
        targetFormatted: 'Rp 10.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 20,
        description: 'Workshop retorika dakwah dan public speaking untuk membekali da\'i muda agar siap berkhutbah dan membina masyarakat.',
        fullDescription: 'Pelatihan intensif retorika, public speaking, dan komunikasi persuasif bagi generasi muda da\'i di Bangka Belitung.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang',
        beneficiaries: 'Da\'i Muda & Relawan',
        featured: false,
        active: true
    },
    {
        id: 'prog-tabligh-akbar',
        slug: 'tabligh-akbar-dzulhijjah',
        title: 'Tabligh Akbar Dzulhijjah',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 15000000,
        targetFormatted: 'Rp 15.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Penyelenggaraan Tabligh Akbar menyambut bulan haram Dzulhijjah dan syiar keutamaan ibadah qurban.',
        fullDescription: 'Menghadirkan kajian akbar tabligh tabligh untuk menggelorakan syiar Islam dan ukhuwah islamiyah di tengah masyarakat.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Masjid Agung & Terbuka',
        beneficiaries: 'Masyarakat Umum',
        featured: false,
        active: true
    },
    {
        id: 'prog-guru-dirosa',
        slug: 'pelatihan-guru-dirosa',
        title: 'Pelatihan Guru Dirosa',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 12000000,
        targetFormatted: 'Rp 12.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 25,
        description: 'Pelatihan standarisasi pengajar metode DIROSA (Pendidikan Al-Qur\'an Orang Dewasa) se-Bangka Belitung.',
        fullDescription: 'Mencetak para pengajar Al-Qur\'an metode cepat bagi orang dewasa guna memberantas buta aksara Al-Qur\'an.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang',
        beneficiaries: 'Calon Guru Dirosa',
        featured: false,
        active: true
    },
    {
        id: 'prog-penyelenggaraan-jenazah',
        slug: 'pelatihan-penyelenggaraan-jenazah',
        title: 'Pelatihan Penyelenggaraan Jenazah',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 8000000,
        targetFormatted: 'Rp 8.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 20,
        description: 'Edukasi dan pelatihan praktik fardhu kifayah tata cara memandikan, mengafani, dan menshalatkan jenazah.',
        fullDescription: 'Pelatihan fardhu kifayah langsung dengan alat peraga untuk membekali masyarakat ilmu syar\'i tata cara pengurusan jenazah.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Masjid & Majelis Taklim',
        beneficiaries: 'Pengurus Masjid & Jamaah',
        featured: false,
        active: true
    },
    {
        id: 'prog-volunteer-media',
        slug: 'pelatihan-volunteer-media-dakwah',
        title: 'Pelatihan Volunteer Media Dakwah',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 10000000,
        targetFormatted: 'Rp 10.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 20,
        description: 'Pelatihan videografi, fotografi jurnalistik, dan copywriting media sosial untuk generasi muda relawan dakwah.',
        fullDescription: 'Membimbing relawan muda dalam memproduksi konten dakwah visual yang estetik, informatif, dan menjangkau ribuan netizen.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang',
        beneficiaries: 'Relawan & Konten Kreator Muda',
        featured: false,
        active: true
    },
    {
        id: 'prog-lomba-poster',
        slug: 'lomba-desain-poster-dakwah',
        title: 'Lomba Desain Poster Dakwah',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 5000000,
        targetFormatted: 'Rp 5.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 15,
        description: 'Kompetisi karya visual kreatif islami untuk mengampanyekan ajakan kebaikan dan nilai-nilai Al-Qur\'an.',
        fullDescription: 'Ajang kreasi desainer grafis muslim di Bangka Belitung untuk menyebarkan pesan dakwah lewat seni visual kreatif.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Online Se-Babel',
        beneficiaries: 'Generasi Muda Kreatif',
        featured: false,
        active: true
    },
    {
        id: 'prog-kantor-dpw',
        slug: 'kantor-dpw-wi-babel-dan-wiz',
        title: 'Kantor DPW WI Babel & WIZ',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 150000000,
        targetFormatted: 'Rp 150.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 90,
        description: 'Pusat pelayanan administrasi ummat, dakwah terpadu, dan kantor Laznas WIZ Bangka Belitung.',
        fullDescription: 'Dukungan operasional dan sarana kantor pusat pelayanan umat dan konsultasi zakat Laznas WIZ Bangka Belitung.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Jl. Ahmad Yani, Pangkalpinang',
        beneficiaries: 'Pelayanan Umat & Donatur',
        featured: false,
        active: true
    },
    {
        id: 'prog-mukerwil',
        slug: 'mukerwil-mukernas-muktamar',
        title: 'Mukerwil Mukernas Muktamar',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Musyawarah kerja tahunan evaluasi program dakwah dan penetapan target keummatan di Bangka Belitung.',
        fullDescription: 'Penyelenggaraan musyawarah kerja tahunan untuk merumuskan arah strategi dakwah dan pelayanan sosial di Bangka Belitung.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Pengurus & Da\'i Se-Babel',
        featured: false,
        active: true
    },
    {
        id: 'prog-dai-pelosok',
        slug: 'keberangkatan-kepulangan-dai',
        title: 'Keberangkatan Kepulangan Dai',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 30000000,
        targetFormatted: 'Rp 30.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 40,
        description: 'Dukungan akomodasi, transportasi, dan kafalah bagi para da\'i yang bertugas di provinsi Bangka Belitung.',
        fullDescription: 'Menjamin transportasi keberangkatan dan kepulangan tugas para da\'i yang mengabdi di pelosok pulau dan desa terpencil.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Da\'i Tugas Pelosok',
        featured: true,
        active: true
    },
    {
        id: 'prog-celengan-subuh',
        slug: 'pengadaan-celengan-sedekah-subuh',
        title: 'Pengadaan Celengan Sedekah Subuh',
        pillar: 'Berkah Hidayah',
        category: 'Dakwah & Pembinaan',
        target: 15000000,
        targetFormatted: 'Rp 15.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Penyediaan sarana kaleng infak harian di rumah, pertokoan, dan perkantoran guna memfasilitasi sedekah subuh.',
        fullDescription: 'Distribusi celengan sedekah subuh ke rumah-rumah donatur untuk membiasakan amalan mulia sedekah di awal waktu subuh.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Keluarga Donatur & Mustahik',
        featured: false,
        active: true
    },

    // ── 3. PILAR BERKAH JUARA (Pendidikan & Beasiswa) ──
    {
        id: 'prog-beasiswa-pendidikan-juara',
        slug: 'beasiswa-pendidikan-juara',
        title: 'Beasiswa Pendidikan Juara',
        pillar: 'Berkah Juara',
        category: 'Pendidikan & Beasiswa',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 45,
        description: 'Bantuan biaya SPP, uang sekolah, dan buku untuk siswa yatim serta dhuafa berprestasi.',
        fullDescription: 'Beasiswa rutin uang sekolah, pembinaan karakter, dan perlengkapan belajar bagi siswa berprestasi dari keluarga kurang mampu.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Siswa Yatim & Dhuafa Berprestasi',
        featured: true,
        urgent: true,
        active: true
    },
    {
        id: 'prog-beasiswa-tahfidz-dhuafa',
        slug: 'beasiswa-tahfidz-dan-dhuafa',
        title: 'Beasiswa Tahfidz & Dhuafa',
        pillar: 'Berkah Juara',
        category: 'Pendidikan & Beasiswa',
        target: 35000000,
        targetFormatted: 'Rp 35.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 50,
        description: 'Beasiswa pendidikan penuh dan asrama bagi santri tahfidz yatim dhuafa di Bangka Belitung.',
        fullDescription: 'Menanggung biaya pendidikan asrama dan konsumsi bagi santri penghafal Quran dari kalangan keluarga yatim dan dhuafa.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pesantren Tahfidz Babel',
        beneficiaries: 'Santri Tahfidz Dhuafa',
        featured: true,
        active: true
    },
    {
        id: 'prog-perlengkapan-belajar-yatim',
        slug: 'perlengkapan-belajar-yatim',
        title: 'Perlengkapan Belajar Yatim',
        pillar: 'Berkah Juara',
        category: 'Pendidikan & Beasiswa',
        target: 15000000,
        targetFormatted: 'Rp 15.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Paket perlengkapan sekolah lengkap (tas, seragam, sepatu, dan buku tulis) menjelang tahun ajaran baru.',
        fullDescription: 'Hadiah paket tas, buku tulis, seragam, dan sepatu baru untuk memotivasi anak-anak yatim menyongsong masa depan cerah.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Anak Yatim & Dhuafa',
        featured: false,
        active: true
    },

    // ── 4. PILAR BERKAH SEHAT (Kesehatan Masyarakat) ──
    {
        id: 'prog-khitanan-massal',
        slug: 'khitanan-massal-dhuafa',
        title: 'Khitanan Massal Dhuafa',
        pillar: 'Berkah Sehat',
        category: 'Kesehatan Masyarakat',
        target: 20000000,
        targetFormatted: 'Rp 20.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 25,
        description: 'Layanan khitanan massal gratis dengan metode modern, pemberian bingkisan pakaian muslim, dan uang santunan.',
        fullDescription: 'Khitan massal bebas biaya dengan metode laser modern yang minim rasa sakit oleh dokter profesional, lengkap dengan bingkisan sarung dan peci.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang & Sungailiat',
        beneficiaries: 'Anak Yatim & Dhuafa',
        featured: true,
        active: true
    },
    {
        id: 'prog-pengobatan-gratis',
        slug: 'layanan-pengobatan-gratis',
        title: 'Layanan Pengobatan Gratis',
        pillar: 'Berkah Sehat',
        category: 'Kesehatan Masyarakat',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Pemeriksaan kesehatan cuma-cuma, cek gula darah & tensi, serta pembagian obat bagi lansia dan dhuafa pelosok.',
        fullDescription: 'Pemeriksaan dokter umum, cek asam urat, gula darah, kolesterol, dan pembagian obat-obatan gratis bagi masyarakat prasejahtera.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Desa-Desa Pelosok Babel',
        beneficiaries: 'Lansia & Warga Prasejahtera',
        featured: false,
        active: true
    },
    {
        id: 'prog-ambulance-gratis',
        slug: 'ambulance-gratis-ummat',
        title: 'Ambulance Gratis Ummat',
        pillar: 'Berkah Sehat',
        category: 'Kesehatan Masyarakat',
        target: 150000000,
        targetFormatted: 'Rp 150.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 75,
        description: 'Layanan antar-jemput pasien gawat darurat dhuafa dan pengantaran jenazah gratis 24 jam di Bangka Belitung.',
        fullDescription: 'Armada ambulans siaga 24 jam tanpa pungutan biaya untuk mengantar pasien gawat darurat, rujukan RS, dan pengantaran jenazah.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pulau Bangka',
        beneficiaries: 'Pasien Gawat Darurat & Dhuafa',
        featured: true,
        urgent: true,
        active: true
    },

    // ── 5. PILAR BERKAH MANDIRI (Ekonomi & Pemberdayaan) ──
    {
        id: 'prog-modal-usaha',
        slug: 'modal-usaha-dhuafa',
        title: 'Modal Usaha Dhuafa',
        pillar: 'Berkah Mandiri',
        category: 'Ekonomi & Pemberdayaan',
        target: 25000000,
        targetFormatted: 'Rp 25.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 40,
        description: 'Bantuan sarana gerobak berkah, permodalan usaha tanpa riba, dan pendampingan usaha kecil bagi keluarga mustahik.',
        fullDescription: 'Pemberian bantuan modal usaha mandiri tanpa bunga serta pendampingan kewirausahaan agar mustahik dapat berdaya dan mandiri.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Pangkalpinang & Sungailiat',
        beneficiaries: 'Pedagang Kecil & Mustahik',
        featured: true,
        active: true
    },
    {
        id: 'prog-pelatihan-wirausaha',
        slug: 'pelatihan-keterampilan-wirausaha',
        title: 'Pelatihan Keterampilan Wirausaha',
        pillar: 'Berkah Mandiri',
        category: 'Ekonomi & Pemberdayaan',
        target: 15000000,
        targetFormatted: 'Rp 15.000.000',
        collected: 0,
        collectedFormatted: 'Rp 0',
        donorsCount: 0,
        daysLeft: 30,
        description: 'Workshop keterampilan digital, pengolahan produk pangan, dan manajemen keuangan keluarga mandiri.',
        fullDescription: 'Pelatihan keterampilan praktis (olahan kuliner, jahit, pemasaran online) untuk membuka peluang usaha baru bagi keluarga prasejahtera.',
        imageUrl: '/assets/images/default-program-wiz.png',
        location: 'Bangka Belitung',
        beneficiaries: 'Ibu Rumah Tangga & Pemuda',
        featured: false,
        active: true
    }
];
